apiVersion: v1
kind: Pod
metadata:
  labels:
    jenkins-agent: react-build-agent
spec:
  serviceAccountName: shiftone-jenkins
  containers:
  - name: nodejs
    image: node:16-alpine
    command:
    - cat
    tty: true
    resources:
      requests:
        cpu: "500m"
        memory: "1Gi"
      limits:
        cpu: "1"
        memory: "2Gi"
    volumeMounts:
    - name: npm-cache
      mountPath: /home/node/.npm
    - name: jenkins-workspace
      mountPath: /home/jenkins/agent
  - name: sonarqube-scanner
    image: sonarsource/sonar-scanner-cli:4.7
    command:
    - cat
    tty: true
    resources:
      requests:
        cpu: "100m"
        memory: "256Mi"
      limits:
        cpu: "200m"
        memory: "512Mi"
  volumes:
  - name: npm-cache
    emptyDir: {}
  - name: jenkins-workspace
    emptyDir: {}
  nodeSelector:
    kubernetes.io/os: linux
  tolerations:
  - key: "jenkins-agent"
    operator: "Equal"
    value: "true"
    effect: "NoSchedule"
